openapi: 3.0.3
info:
  title: Flight Search API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /flights/search:
    post:
      tags:
        - flight
      summary: Search flights
      operationId: flight_search
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightSearchRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightSearchResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /flights/create:
    post:
      tags:
        - flight
      summary: Create flight
      operationId: flight_create
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /flights/{flightId}/update:
    post:
      tags:
        - flight
      summary: Update flight
      operationId: flight_update
      security:
        - bearerAuth: []
      parameters:
        - name: flightId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlightRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /flights/{flightId}:
    get:
      tags:
        - flight
      summary: Get flight by id
      operationId: flight_getById
      security:
        - bearerAuth: []
      parameters:
        - name: flightId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /flights/{flightId}/delete:
    get:
      tags:
        - flight
      summary: Delete flight by id
      operationId: flight_delete
      security:
        - bearerAuth: []
      parameters:
        - name: flightId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /airports/search:
    post:
      tags:
        - airport
      summary: Search airport
      operationId: airport_search
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirportSearchRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportSearchResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /airports/create:
    post:
      tags:
        - airport
      summary: Create airport
      operationId: airport_create
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirportRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /airports/{airportId}/update:
    post:
      tags:
        - airport
      summary: Update airport
      operationId: airport_update
      security:
        - bearerAuth: []
      parameters:
        - name: airportId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirportRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /airports/{airportId}:
    get:
      tags:
        - airport
      summary: Get airport by id
      operationId: airport_getById
      security:
        - bearerAuth: []
      parameters:
        - name: airportId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /airports/{airportId}/delete:
    get:
      tags:
        - airport
      summary: Delete airport by id
      operationId: airport_delete
      security:
        - bearerAuth: []
      parameters:
        - name: airportId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - auth
      summary: Login
      operationId: auth_login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLoginRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    FlightRequest:
      type: object
      required:
        - originAirportId
        - destinationAirportId
        - departureDate
        - price
      properties:
        originAirportId:
          type: integer
          format: int64
        destinationAirportId:
          type: integer
          format: int64
        departureDate:
          type: string
          format: date-time
        returnDate:
          type: string
          format: date-time
        price:
          $ref: '#/components/schemas/Price'

    AirportRequest:
      type: object
      required:
        - city
      properties:
        city:
          type: string

    FlightSearchRequest:
      type: object
      required:
        - originAirportId
        - destinationAirportId
        - departureDate
      properties:
        originAirportId:
          type: integer
          format: int64
          nullable: false
        destinationAirportId:
          type: integer
          format: int64
        departureDate:
          type: string
          format: date
        returnDate:
          type: string
          format: date
        pageRequest:
          $ref: '#/components/schemas/PageRequest'

    Flight:
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/Airport'
        destination:
          $ref: '#/components/schemas/Airport'
        departureDate:
          type: string
          format: date-time
        price:
          $ref: '#/components/schemas/Price'

    FlightSearchResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Journey'

    Journey:
      type: object
      properties:
        id:
          type: integer
          format: int64
        price:
          $ref: '#/components/schemas/Price'
        type:
          $ref: '#/components/schemas/JourneyType'
        outbound:
          $ref: '#/components/schemas/Flight'
        inbound:
          $ref: '#/components/schemas/Flight'


    JourneyType:
      type: string
      enum: [OUTBOUND, ROUND_TRIP]

    Price:
      type: object
      properties:
        amount:
          type: number
          format: double
        currency:
          type: string


    Airport:
      type: object
      properties:
        id:
          type: integer
          format: int64
        city:
          type: string

    AirportSearchRequest:
      type: object
      properties:
        term:
          type: string
        pageRequest:
          $ref: '#/components/schemas/PageRequest'

    AirportSearchResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Airport'

    AuthLoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    Token:
      type: object
      properties:
        value:
          type: string
        validUntil:
          type: string
          format: date-time
        role:
          $ref: '#/components/schemas/Role'

    Role:
      type: object
      properties:
        name:
          type: string
          enum: [ADMIN, STANDARD]
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

    Permission:
      type: string
      enum: [READ, WRITE]

    PageRequest:
      type: object
      properties:
        start:
          type: integer
          default: 0
          minimum: 0
        limit:
          type: integer
          default: 20
          minimum: 0
        order:
          $ref: '#/components/schemas/Order'

    Order:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/OrderSort'
        direction:
          $ref: '#/components/schemas/OrderDirection'

    OrderSort:
      type: string
      enum: [PRICE, DATE, CITY]
      default: DATE

    OrderDirection:
      type: string
      enum: [ASC, DESC]
      default: ASC


    Error:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        cause:
          type: string

    ErrorCode:
      type: string
      enum: [
        INVALID_INPUT,
        NOT_FOUND,
        SERVER_ERROR,
        AUTH_ERROR,
        FORBIDDEN,
        UNAUTHORIZED
      ]

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

