spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

mock:
  api:
    url: https://65a2bd4a42ecd7d7f0a828ac.mockapi.io/api/

tasks:
  cron:
    fetchdata: 0 0 1 * * *