spring:
  datasource:
    url: jdbc:postgresql://localhost:1212/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}